### Get a list of the most recent 10 Repositories
GET http://localhost:3000/api/github/repos
Content-Type: application/json

### Check, if a specific repo exists
GET http://localhost:3000/api/github/repoexists
Content-Type: application/json

{
    "repo": "klemmer.info"
}

### Calling the original Github API
GET https://api.github.com/repos/tobkle/klemmer.info
Content-Type: application/vnd.github.v3+json

